---
output: html_document
---
<center>

# Used Motor Oil Disposal Locations
#### City of Ottawa used oil ["Take it back!" member](http://app06.ottawa.ca/online_services/recycling/items/371_en.html) businesses 


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(leaflet)

```

```{r get_data, eval=F, include = F}

library(rvest)
library(ggmap)
# Run the following code to if there are changes to the list of locations 
# provided by The City or if the page location moves
url <- "http://app06.ottawa.ca/online_services/recycling/items/371_en.html"
html <- read_html(url)

# Web scrape
# found CSS element ".tibpartners td" using https://selectorgadget.com
d <- data.frame(matrix(html_text(html_nodes(html, ".tibpartners td")), 
                       ncol = 3, 
                       byrow = T, 
                       dimnames = list(NULL,c("Name", 
                                              "Short_address", 
                                              "Phone"))))

d$Long_address <- paste0(d$Short_address, ", Ottawa")
d$lon <- NA_real_
d$lat <- NA_real_
d$address <- NA_character_

# Brute force geolocation seach using google maps API
while(any(is.na(d$lon), is.na(d$lat))){
  for(i in 1:nrow(d)){
    if(any(is.na(d[i,]$lon), is.na(d[i,]$lat))) {
      d[i,c("lon", "lat","address")] <- geocode(d[i,"Long_address"], output = "latlona", source = "google", override_limit = T)
    }
  }  
}

write_csv(d, "~/Dropbox/R/Oil_recycle_ottawa/locations.csv")

```

```{r make_map, fig.align="center", echo = F}

d <- read.csv("~/Dropbox/R/ottawa_motor_oil_disposal/locations.csv")

the_map <- leaflet() %>% 
  setMaxBounds(lng1 = -76.05, 
               lat1 = 45.05, 
               lng2 = -75.4, 
               lat2 = 45.55) %>%
  addTiles() %>% 
  addCircleMarkers(lng = d$lon, 
             lat = d$lat, 
             popup = paste(sep = "<br/>",
                           "<b>", d$Name, "</b>",
                           d$Short_address,
                           d$Phone)
             )
the_map

```

<i>
Accuracy of provided information is not guaranteed.<br>
Contact businesses to verify they will accept your used oil.
</i>


---

```{r make_table, echo = F}

library(knitr)
kable(d[, c("Name", "Short_address", "Phone")], 
      col.names = c("Business Name", "Address", "Phone"))

```

</center>